Change recommendations to prefer Bash on Windows #10
JMoVS/installing_video_transcoding_on_windows pull request #11
Opened 2017-06-30 11:03 UTC by samhutchins

Rework the README to recommend using Bash on Ubuntu on Windows,
and pull everything into one README

Is there any information that's been lost that you want to preserve?

Can you also check my spelling/typos. I invariably read what I meant to write, not what's written.

2017-07-03 13:43 UTC, JMoVS commented
I will take some days. I think when I'm in Cusco, I should find the minute to review it (I'm currently traveling through South America)

2017-07-05 18:49 UTC, JMoVS requested changes
Very nice new document! I have some remaining questions but all in all I think this will improve usability a lot!

2017-07-05 18:49 UTC, JMoVS commented on README.md
> +    1. Select `Windows Subsystem for Linux (beta)`
Did you test it this way? Is it not needed to go to the Windows Store and actually click the "download" button on Ubuntu for Windows?

2017-07-05 18:49 UTC, JMoVS commented on README.md
> +    1. Fire up bash
Firing up bash can be quite difficult as sometimes, Windows didn't show it in search and the icon on the desktop only appearts after you accept the license agreement

2017-07-05 18:49 UTC, JMoVS commented on README.md
> +    1. Run `sudo apt-get update && sudo apt-get upgrade` to ensure everything's up to date
Also, the first time you run bash, it asks you to create a user and a password, should we mention that here as well?

2017-07-05 18:49 UTC, JMoVS commented on README.md
> +The `detect-crop` command has an optional dependency on `mpv` for previewing crops. You can't launch graphical Linux apps using "Bash on Ubuntu on Windows", but it is capable of launching Windows pro
I've heard that one could install a window manager like kde, so thereby possibly also launching mpv? :P

Also "this" means.

2017-07-05 18:49 UTC, JMoVS commented on README.md
> +The `detect-crop` command has an optional dependency on `mpv` for previewing crops. You can't launch graphical Linux apps using "Bash on Ubuntu on Windows", but it is capable of launching Windows pro
"this" means we can install `mpv` for Windows (comma or "and")

2017-07-05 18:49 UTC, JMoVS commented on README.md
> +If you have your movie files in the Windows file system (so NOT in `~userfolder/AppData/Local/lxss/home`), for example on your desktop, you have to provide the path to it via `/mnt/[drive letter]/pat
oh cool, didn't know that trick with bash in the address bar!

2017-07-05 18:49 UTC, JMoVS commented on README.md
> +In old versions of Windows 10, or in Windows 8.1 and earlier you either  don't have access to Bash on Ubuntu on Windows, or the version that's there can't be used to do this. But no matter! All the d
Is "But no matter!" a colloquialism that works in English?

2017-07-05 18:49 UTC, JMoVS commented on README.md
> +It works in much the same way that Don's [bash script](https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video) works, although it does have the limitation of not being able
I didn't look into the batch script that much to be honest, but what is limiting the resuming functionality?

2017-07-05 19:40 UTC, samhutchins commented on README.md
> +    1. Select `Windows Subsystem for Linux (beta)`
It's not in the store. I think it's planned, but it's not there yet. Not in the UK at least.

2017-07-05 19:41 UTC, samhutchins commented on README.md
> +    1. Fire up bash
By this point people have run bash from CMD and got it all set up, including accepting license agreements. It should be visible in the start menu. How would you recommend starting bash?

2017-07-05 19:42 UTC, samhutchins commented on README.md
> +    1. Run `sudo apt-get update && sudo apt-get upgrade` to ensure everything's up to date
I'll add a note about that

2017-07-05 19:43 UTC, samhutchins commented on README.md
> +The `detect-crop` command has an optional dependency on `mpv` for previewing crops. You can't launch graphical Linux apps using "Bash on Ubuntu on Windows", but it is capable of launching Windows pro
It's possible, I've got an X server in Windows that lets me use `git-gui` and `meld`. I can test mpv, but I don't have high hopes about it's performance

2017-07-05 19:44 UTC, samhutchins commented on README.md
> +If you have your movie files in the Windows file system (so NOT in `~userfolder/AppData/Local/lxss/home`), for example on your desktop, you have to provide the path to it via `/mnt/[drive letter]/pat
It's a damn useful trick. Works with cmd and powershell too

2017-07-05 19:45 UTC, samhutchins commented on README.md
> +In old versions of Windows 10, or in Windows 8.1 and earlier you either  don't have access to Bash on Ubuntu on Windows, or the version that's there can't be used to do this. But no matter! All the d
Yeah, informal English. I'll remove it, I don't think it quite works

2017-07-05 19:46 UTC, samhutchins commented on README.md
> +It works in much the same way that Don's [bash script](https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video) works, although it does have the limitation of not being able
Don's shell script modifies the queue.txt to remove items it's already encoded, but I'm not aware of an easy built in way to do that in a batch file

2017-07-05 22:56 UTC, JMoVS requested changes
I went over it completely and from my side, this is really good! Do we want to open a separate pull request about how to update the different setups or do we want to include a "how to update" section in the additional info in this PR already?

2017-07-05 22:56 UTC, JMoVS commented on README.md
> +Don Melton provides some [amazing scripts](https://github.com/donmelton/video_transcoding) that wrap [HandBrake](https://handbrake.fr/) to produce high quality, portable versions of Blu Ray rips. The
I just noticed one more request, sorry for not including it earlier. I think we should reverse the order of "hunting down binaries or lxss method". For me the first option sounds like the suggested/recommended one (even though it isn't anymore). 

Maybe something like
"Using [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-gb/commandline/wsl/about) (default and recommended) or downloading binaries manually (for older Windows versions) are two such that are covered here."

2017-07-05 22:56 UTC, JMoVS commented on README.md
> +    1. Select `Windows Subsystem for Linux (beta)`
Hmm, Even if you search for Ubuntu? Strange, anyway, you tested it and it worked so 👍

2017-07-05 22:56 UTC, JMoVS commented on README.md
> +Don Melton provides some [amazing scripts](https://github.com/donmelton/video_transcoding) that wrap [HandBrake](https://handbrake.fr/) to produce high quality, portable versions of Blu Ray rips. The
... BlueRay and DVD rips.

2017-07-05 22:56 UTC, JMoVS commented on README.md
> +If you're using an up-to-date version of Windows 10, you have access to "[Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-gb/commandline/wsl/about)". This feature allows you to run command l
I don't know how perfectionistic we want to go about this (in all seriousness), a small thing is that it changes person from "you have access to Bash..." to "gives *us* access to..."

2017-07-05 22:56 UTC, JMoVS commented on README.md
> +## Transcoding video on Windows, the Don Melton way
@donmelton Checking with you if you are fine with us naming this document this way? Is this ok for you? It implies an implcit approval of the outlined method from you, so checking with you in advance.

2017-07-05 22:56 UTC, JMoVS commented on README.md
> +If you're using an up-to-date version of Windows 10, you have access to "[Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-gb/commandline/wsl/about)". This feature allows you to run command l
Also from addressing the reader as "you", it changes to "everything *we* need to run"

2017-07-05 22:56 UTC, JMoVS commented on README.md
> +If you have your movie files in the Windows file system (so NOT in `~userfolder/AppData/Local/lxss/home`), for example on your desktop, you have to provide the path to it via `/mnt/[drive letter]/pat
Super pedantic little things: Are there spaces after the `s ? Do you think it looks better with a soace? I trust your judgement there.

2017-07-05 22:56 UTC, JMoVS commented on README.md
> +    Functional Windows binaries for this are hard to find, I've been using [this one](http://forum.doom9.org/showthread.php?t=171038). If anyone knows of a more official binary, please let me know
I think we should make the "please let me know" either a link to a new bug report or ot your email/twitter, so people could actually figure out quickly who,pm to contact (you).

2017-07-06 00:03 UTC, JMoVS commented on README.md
> +Don Melton provides some [amazing scripts](https://github.com/donmelton/video_transcoding) that wrap [HandBrake](https://handbrake.fr/) to produce high quality, portable versions of Blu Ray rips. The
Blue-ray

2017-07-10 11:40 UTC, samhutchins commented on README.md
> +If you have your movie files in the Windows file system (so NOT in `~userfolder/AppData/Local/lxss/home`), for example on your desktop, you have to provide the path to it via `/mnt/[drive letter]/pat
No spaces

2017-07-10 11:44 UTC, samhutchins commented on README.md
> +Don Melton provides some [amazing scripts](https://github.com/donmelton/video_transcoding) that wrap [HandBrake](https://handbrake.fr/) to produce high quality, portable versions of Blu Ray rips. The
Blu-ray is the correct spelling

2017-07-10 11:45 UTC, samhutchins commented on README.md
> +If you're using an up-to-date version of Windows 10, you have access to "[Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-gb/commandline/wsl/about)". This feature allows you to run command l
I'll use you consistently

2017-07-10 15:00 UTC, JMoVS approved these changes

2017-07-10 15:03 UTC, JMoVS commented
I'm gona squash and merge this now. I don't care enough about commit message typos ;-)

2017-07-10 15:09 UTC, JMoVS commented
managed to clean up the commit messages, merging now.

2017-07-10 15:10 UTC, merged

2017-07-10 15:10 UTC, JMoVS commented
Turns out, I would have been able to modify the commit message on the webinterface as well - well...