Rev Windows Subsystem for Linux instructions
JMoVS/installing_video_transcoding_on_windows pull request #8
Opened 2017-05-24 19:17 UTC by samhutchins

The Windows Creator's update is out, and using the Windows Subsystem for Linux to install these tools is much easier

2017-05-24 19:18 UTC, samhutchins commented
Paging @donmelton for his thoughts too

2017-05-24 21:07 UTC, donmelton commented
@samhutchins Well, my first thought is that this seems a _lot_ simpler now. And I assume this really is easier too? That is, not fraught with as many gotchas?

2017-05-24 21:14 UTC, samhutchins commented
The big gotcha is that the output from handbrake seems to bring the whole system to a crawl. I presume it's a bug in lxss, but it seems to struggle with that many console writes :-(

But yeah, it's a lot easier to install these tools in lxss now than it used to be, but I still prefer using windows builds because of the issue noted above.

2017-05-24 22:45 UTC, donmelton commented
@samhutchins That's one weird damn bug then. Does it compromise the speed of transcoding?

2017-05-25 00:48 UTC, JMoVS requested changes
This is phenomenal! I currently don't have a windows 10 VM handy to test, but this seems incredibly more easy, and seems to be even easier than the manual binary method. ~Before we go live, what do you think of using this as the new preferred method and thereby requiring a change to the top level readme as well?~ I think you're right, but see my last comment. We could also do the reverse things and just call the linux binaries from within cmd.exe/powershell. Does that solve the output speed issue of Handbrake-log?

Not directly related to the creators update but related to the review of the instructions, I think we should add "or drag and drop the files in to provide the path" to the caveats section with the file path here.

2017-05-25 00:53 UTC, JMoVS commented
@samhutchins I think we should open an issue on Microsofts githup repo of the windows subsystem on linux on this and see what they think of this - whether this is some weird bug with a lot of console output.

2017-05-25 01:17 UTC, JMoVS commented
@samhutchins I think we should open an issue on Microsofts githup repo of the windows subsystem on linux on this and see what they think of it. What do you think?

2017-05-25 08:21 UTC, samhutchins commented
@JMoVS I think we should do some work to be sure sure it's a bug in their system, and not one they're already aware of

@donmelton The performance of the encode doesn't seem to be much affected, it just feels a bit unresponsive while the transcode is happening

I'll try to capture a video to show the issue

Other thoughts:

- The laggy console output only happens when calling Handbrake via Ruby, if I call it directly it's all fine
- I can't recommend doing this over the other method because step one for this is "put your PC in developer mode".
- Calling linux binaries from CMD.exe doesn't solve the laggy terminal and introduces a whole new layer of complexity

2017-05-25 10:30 UTC, JMoVS commented
I sort of remember that somewhere, somebody already talked about lxss getting slow when a lotmofnlines are output. Was that here? Really not sure right now (and a quick Google search didn't show anything promising either). 

Why do you think putting the computer in developer mode is not good? We're asking people to work in a shell, modifiy PATH and put /random/ binaires in specific places. 

Does it make a difference when you run it in PowerShell instead of cmd.exe?

2017-05-25 11:21 UTC, samhutchins commented
You raise a fair point about PATH modification and random binaries...

I dunno, I've always felt that developer mode makes a system a little less secure, but I don't actually *know* that that's the case on Windows. Perhaps I'm already becoming a bit stuck in my ways, I've always just used CMD and whatever windows binaries I can find for any command line work.

---

I've tried launching bash from the start menu, from cmd, from powershell, and from ConEmu; it's all the same. Given how it doesn't actually affect the transcode speed it's probably not that big a deal, it just feels weird

It's worth noting that in order to preview crops using mpv you need to do PATH modification regardless of how you install everything else. Unless there's a nicely wrapped up MPV installer that I'm not aware of

2017-05-29 17:22 UTC, JMoVS commented
Ok, I will try to get it setup with my Dad soon. If it passes the Dad test, I think it has pro's and con's. Let's reevaluate this soon - I don't think I can try to get it working with my dad before the coming weekend, so I still need some time.

But as these instructions are lightyears better than what was before, I'll merge them now and treat the new recommendation as a separate PR then. Thank you very very much @samhutchins!

2017-05-29 17:22 UTC, merged